  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_URL}
      VITE_API_KEY: ${VITE_API_KEY}
      VITE_AUTH_DOMAIN: ${VITE_AUTH_DOMAIN}
      VITE_PROJECT_ID: ${VITE_PROJECT_ID}
      VITE_STORAGE_BUCKET: ${VITE_STORAGE_BUCKET}
      VITE_MESSAGING_SENDER_ID: ${VITE_MESSAGING_SENDER_ID}
      VITE_APP_ID: ${VITE_APP_ID}
      VITE_MEASUREMENT_ID: ${VITE_MEASUREMENT_ID}
